title: Hi! I am Maya
description: CSP 2025-2026
owner_name: Maya Drukin
github_username: maya-dn 
github_repo: "CSP-team" 
url: "https://CSP-personal"
baseurl: "/CSP-personal" 
future: true

remote_theme: jekyll-theme-minima

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/open-coding-society" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.mdhgh

include:
  - assets